<?php

use Illuminate\Database\Seeder;

class RulesTableSeeder extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table("rules")->insert([[
                "id"=>"1",
                "pid"=>"0",
                "title"=>"会员系统",
                "rule"=>"",
                "desc"=>"",
                "type"=>"1",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"2",
                "pid"=>"0",
                "title"=>"内容管理",
                "rule"=>"",
                "desc"=>"",
                "type"=>"1",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"3",
                "pid"=>"0",
                "title"=>"权限系统",
                "rule"=>"",
                "desc"=>"",
                "type"=>"1",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"4",
                "pid"=>"0",
                "title"=>"其他管理",
                "rule"=>"",
                "desc"=>"",
                "type"=>"1",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"5",
                "pid"=>"1",
                "title"=>"会员列表",
                "rule"=>"admin/user/list",
                "desc"=>"",
                "type"=>"2",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"6",
                "pid"=>"5",
                "title"=>"会员检索",
                "rule"=>"admin/user/search",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"7",
                "pid"=>"5",
                "title"=>"会员搜索",
                "rule"=>"admin/user/keyword",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"8",
                "pid"=>"5",
                "title"=>"会员详情",
                "rule"=>"admin/user/detail",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"9",
                "pid"=>"5",
                "title"=>"会员冻结",
                "rule"=>"admin/user/freeze",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"10",
                "pid"=>"5",
                "title"=>"会员解冻",
                "rule"=>"admin/user/unfreeze",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"11",
                "pid"=>"5",
                "title"=>"会员冻结历史",
                "rule"=>"admin/user/freeze/list",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"12",
                "pid"=>"5",
                "title"=>"会员冻结状态",
                "rule"=>"admin/user/freeze/detail",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"13",
                "pid"=>"2",
                "title"=>"标签",
                "rule"=>"admin/label/list",
                "desc"=>"",
                "type"=>"2",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"14",
                "pid"=>"13",
                "title"=>"标签添加",
                "rule"=>"admin/label/add",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"15",
                "pid"=>"13",
                "title"=>"标签修改",
                "rule"=>"admin/label/update",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"16",
                "pid"=>"13",
                "title"=>"标签详情",
                "rule"=>"admin/label/detail",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"17",
                "pid"=>"13",
                "title"=>"标签排序",
                "rule"=>"admin/label/sort",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"18",
                "pid"=>"13",
                "title"=>"标签删除",
                "rule"=>"admin/label/delete",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"19",
                "pid"=>"2",
                "title"=>"资讯分类",
                "rule"=>"admin/category/list",
                "desc"=>"",
                "type"=>"2",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"20",
                "pid"=>"19",
                "title"=>"资讯分类添加",
                "rule"=>"admin/category/add",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"21",
                "pid"=>"19",
                "title"=>"资讯分类修改",
                "rule"=>"admin/category/update",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"22",
                "pid"=>"19",
                "title"=>"资讯分类检索",
                "rule"=>"admin/category/search",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"23",
                "pid"=>"19",
                "title"=>"资讯分类详情",
                "rule"=>"admin/category/detail",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"24",
                "pid"=>"19",
                "title"=>"资讯分类排序",
                "rule"=>"admin/category/sort",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"25",
                "pid"=>"19",
                "title"=>"资讯分类冻结",
                "rule"=>"admin/category/freeze",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"26",
                "pid"=>"19",
                "title"=>"资讯分类解冻",
                "rule"=>"admin/category/unfreeze",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"27",
                "pid"=>"19",
                "title"=>"资讯分类推荐",
                "rule"=>"admin/category/hot",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"28",
                "pid"=>"19",
                "title"=>"资讯分类删除",
                "rule"=>"admin/category/delete",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"29",
                "pid"=>"2",
                "title"=>"资讯管理",
                "rule"=>"admin/info/list",
                "desc"=>"",
                "type"=>"2",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"30",
                "pid"=>"29",
                "title"=>"资讯添加",
                "rule"=>"admin/info/add",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"31",
                "pid"=>"29",
                "title"=>"资讯修改",
                "rule"=>"admin/info/update",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"32",
                "pid"=>"29",
                "title"=>"资讯检索",
                "rule"=>"admin/info/search",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"33",
                "pid"=>"29",
                "title"=>"资讯搜索",
                "rule"=>"admin/info/keyword",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"34",
                "pid"=>"29",
                "title"=>"资讯详情",
                "rule"=>"admin/info/detail",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"35",
                "pid"=>"29",
                "title"=>"资讯排序",
                "rule"=>"admin/info/sort",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"36",
                "pid"=>"29",
                "title"=>"资讯冻结",
                "rule"=>"admin/info/freeze",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"37",
                "pid"=>"29",
                "title"=>"资讯解冻",
                "rule"=>"admin/info/unfreeze",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"38",
                "pid"=>"29",
                "title"=>"资讯置顶",
                "rule"=>"admin/info/top",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"39",
                "pid"=>"29",
                "title"=>"资讯取消置顶",
                "rule"=>"admin/info/down",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"40",
                "pid"=>"29",
                "title"=>"资讯删除",
                "rule"=>"admin/info/delete",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"41",
                "pid"=>"2",
                "title"=>"单页内容",
                "rule"=>"admin/content/list",
                "desc"=>"",
                "type"=>"2",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"42",
                "pid"=>"41",
                "title"=>"单页内容添加",
                "rule"=>"admin/content/add",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"43",
                "pid"=>"41",
                "title"=>"单页内容修改",
                "rule"=>"admin/content/update",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"44",
                "pid"=>"41",
                "title"=>"单页内容检索",
                "rule"=>"admin/content/search",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"45",
                "pid"=>"41",
                "title"=>"单页内容详情",
                "rule"=>"admin/content/detail",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"46",
                "pid"=>"41",
                "title"=>"单页内容删除",
                "rule"=>"admin/content/delete",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"47",
                "pid"=>"2",
                "title"=>"banner管理",
                "rule"=>"admin/banner/list",
                "desc"=>"",
                "type"=>"2",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"48",
                "pid"=>"47",
                "title"=>"banner添加",
                "rule"=>"admin/banner/add",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"49",
                "pid"=>"47",
                "title"=>"banner修改",
                "rule"=>"admin/banner/update",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"50",
                "pid"=>"47",
                "title"=>"banner检索",
                "rule"=>"admin/banner/search",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"51",
                "pid"=>"47",
                "title"=>"banner搜索",
                "rule"=>"admin/banner/keyword",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"52",
                "pid"=>"47",
                "title"=>"banner详情",
                "rule"=>"admin/banner/detail",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"53",
                "pid"=>"47",
                "title"=>"banner排序",
                "rule"=>"admin/banner/sort",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"54",
                "pid"=>"47",
                "title"=>"banner推荐",
                "rule"=>"admin/banner/hot",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"55",
                "pid"=>"47",
                "title"=>"banner冻结",
                "rule"=>"admin/banner/freeze",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"56",
                "pid"=>"47",
                "title"=>"banner解冻",
                "rule"=>"admin/banner/unfreeze",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"57",
                "pid"=>"47",
                "title"=>"banner删除",
                "rule"=>"admin/banner/delete",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"58",
                "pid"=>"3",
                "title"=>"管理员",
                "rule"=>"admin/list",
                "desc"=>"",
                "type"=>"2",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"59",
                "pid"=>"58",
                "title"=>"管理员添加",
                "rule"=>"admin/add",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"60",
                "pid"=>"58",
                "title"=>"管理员修改",
                "rule"=>"admin/update",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"61",
                "pid"=>"58",
                "title"=>"管理员详情",
                "rule"=>"admin/detail",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"62",
                "pid"=>"58",
                "title"=>"管理员冻结",
                "rule"=>"admin/freeze",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"63",
                "pid"=>"58",
                "title"=>"管理员解冻",
                "rule"=>"admin/unfreeze",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"64",
                "pid"=>"58",
                "title"=>"管理员删除",
                "rule"=>"admin/delete",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"65",
                "pid"=>"58",
                "title"=>"管理员修改密码",
                "rule"=>"admin/password",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"66",
                "pid"=>"3",
                "title"=>"管理组",
                "rule"=>"admin/group/list",
                "desc"=>"",
                "type"=>"2",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"67",
                "pid"=>"66",
                "title"=>"管理组添加",
                "rule"=>"admin/group/add",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"68",
                "pid"=>"66",
                "title"=>"管理组修改",
                "rule"=>"admin/group/update",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"69",
                "pid"=>"66",
                "title"=>"管理组详情",
                "rule"=>"admin/group/detail",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"70",
                "pid"=>"66",
                "title"=>"管理组删除",
                "rule"=>"admin/group/delete",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"71",
                "pid"=>"66",
                "title"=>"管理组权限详情",
                "rule"=>"admin/rule/detail",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"72",
                "pid"=>"66",
                "title"=>"管理组设置权限",
                "rule"=>"admin/rule/update",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"73",
                "pid"=>"4",
                "title"=>"表单提交管理",
                "rule"=>"admin/contact/list",
                "desc"=>"",
                "type"=>"2",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"74",
                "pid"=>"73",
                "title"=>"表单提交处理",
                "rule"=>"admin/contact/update",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"75",
                "pid"=>"4",
                "title"=>"开屏广告图管理",
                "rule"=>"admin/ad/list",
                "desc"=>"",
                "type"=>"2",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"76",
                "pid"=>"75",
                "title"=>"开屏广告图添加",
                "rule"=>"admin/ad/add",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"77",
                "pid"=>"75",
                "title"=>"开屏广告图修改",
                "rule"=>"admin/ad/update",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"78",
                "pid"=>"75",
                "title"=>"开屏广告图搜索",
                "rule"=>"admin/ad/keyword",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"79",
                "pid"=>"75",
                "title"=>"开屏广告图详情",
                "rule"=>"admin/ad/detail",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"80",
                "pid"=>"75",
                "title"=>"开屏广告图排序",
                "rule"=>"admin/ad/sort",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"81",
                "pid"=>"75",
                "title"=>"开屏广告图冻结",
                "rule"=>"admin/ad/freeze",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"82",
                "pid"=>"75",
                "title"=>"开屏广告图解冻",
                "rule"=>"admin/ad/unfreeze",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"83",
                "pid"=>"75",
                "title"=>"开屏广告图删除",
                "rule"=>"admin/ad/delete",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"84",
                "pid"=>"4",
                "title"=>"ios版本号",
                "rule"=>"admin/version/ios/detail",
                "desc"=>"",
                "type"=>"2",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"85",
                "pid"=>"84",
                "title"=>"ios版本号修改",
                "rule"=>"admin/version/ios/update",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"86",
                "pid"=>"4",
                "title"=>"安卓版本号",
                "rule"=>"admin/version/andriod/detail",
                "desc"=>"",
                "type"=>"2",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"87",
                "pid"=>"86",
                "title"=>"安卓版本号修改",
                "rule"=>"admin/version/andriod/update",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ],[
                "id"=>"88",
                "pid"=>"58",
                "title"=>"管理员登出",
                "rule"=>"admin/logout",
                "desc"=>"",
                "type"=>"3",
                "status"=>"1",
                "path"=>"",
                "created_at"=>"2018-12-17 17:06:11",
                "updated_at"=>"2018-12-17 17:06:11",
            ]
        ]);
    }
}
